### PR TITLE
Native library bindings

### LINKED ISSUE #3: Implement native library bindings
# Mechanism:

1. User provides some type of config file that describes library function signatures and classes

For example:
```json
{
    "library": "InstanceMeta",
    "functions": [
        {
            "export": "getField",
            "args": [
                "ObjInstance",
                "ObjString"
            ],
            "returns": "Value"
        }
    ]
}
```
2. This will be used to generate wrappers around user-provided functions. An example wrapper would  look like
```c
#include "native_binding.h"

ValueResult getField(ObjInstance* instance, ObjString* field);

bool getFieldImpl(int argCount, Value* implicit, Value* args) {
   if (!IS_INSTANCE(args[0])) {
        *implicit = NATIVE_ERROR("Function 'hasField' expects an instance as the first argument.");
        return false;
    }
    if (!IS_STRING(args[1])) {
        *implicit = NATIVE_ERROR("Function 'hasField' expects a string as the second argument.");
        return false;
    }
   ObjInstance* instance = AS_INSTANCE(args[0]);
   ObjString* key = AS_STRING(args[1]);

   ValueResult result = getField(instance, key);
   if (result.exception != NULL) {
       *implicit = NATIVE_ERROR(result.exception);
       return false;
    }

    *implicit = result.result;
    return true;
}

static LibHandle * lib_ptr;

extern void lib_init(); // weak, with do-nothing, can be redefined by user, PRIVATE visibility
extern void lib_deinit(); // weak, with do-nothing, can be redefined by user, PRIVATE visibility

void __attribute__ ((constructor)) constructor()  {
    lib_init();
    LibHandle * lib = registerLibrary("InstanceMeta");
    registerNativeFunction(lib, "getField", getField);
    lib_ptr = lib;
}

void __attribute__ ((constructor)) destructor() {
    lib_deinit();
} 

```
3.  User provides C their implementations files with the signatures like so:
```c
GetFieldResult getField(ObjInstance* instance, ObjString* field) {
    Value value;
    if (!tableGet(&instance->fields, key, &value)) {
        return (ValueResult) { .exception =  "Instance doesn't have the required field"}; 
    }

   return value;
}
```
4. User compiles their files with the generated file into a shared library. They can optionally provide InstanceMeta.lox.native file with lox declarations, as a library interface description for tooling and library users.

### LINKED ISSUE #21: Refactor test structure
Tests should be placed close to the code they are testing. 
This enables testing small components of the project that are not complete logical units, without making them fully public targets.
This also keeps tests close to the code.

### LINKED ISSUE #23: Refactor the runtime library
Native bindings need access to the runtime library. This is currently a part of the `libcloximpl.so`. Split this library so that native bindings can interop with the runtime.

### LINKED ISSUE #33: Refactor project structure
Current project structure is impractical. It should be restructured to be flatter at top level.

### PR DESCRIPTION
**Pull request by lordofdestiny**
Implement a mechanism for automatically generating bindings for native libraries with a standardized interface. 

Provide 3 types of bindings:
- Wrapped and non-failing functions
  Wrapped functions returns unwrapped C types
- Wrapped and failing functions
  Function returns `<Type>Result` type, a`union` with `result` and `exception`
- Unwrapped functions
  Implementation manually checks passed arguments

- Refactor project structure
- Refactor scanner API

Issues:
- Resolves #3 
- Resolves #21
- Resolves #23
- Resolves #33

### CODE REVIEW

File: lib/impl/src/table.c [hunk 1]
```diff
@@ -73,7 +72,9 @@ bool tableGet(Table* table, ObjString* key, Value* value) {
     const Entry* entry = findEntry(table->entries, table->capacity, key);
     if (entry->key == NULL) return false;
 
-    *value = entry->value;
+    if (value != NULL) {
+        *value = entry->value;
+    }
```
Comment (lordofdestiny) [inline lib/impl/src/table.c]: This enables `tableGet(table, key, NULL)` to have semantics of `hasKey(table, key)`
